title: Bilal Kahraman
description: "The Illuminati doesn't run the world. C programmers do."
show_downloads: false
google_analytics: false
theme: jekyll-theme-hacker

author:
  name: "Bilal Kahraman"
  email: "kahramannbilal@gmail.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "bilalkah"
year : "2021"